---
prometheus::manage_prometheus_server: true

prometheus::version: '2.27.0'

prometheus::alerts:
  groups:
    - name: 'alert.rules'
      rules:
        - alert: 'InstanceDown'
          expr: 'up == 0'
          for: '1m'
          labels:
            severity: 'page'
          annotations:
            summary: 'Instance {{ .Labels.instance }} {{ .Value }} down'
            description: '{{ $labels.instance }} of job {{ $labels.job }} has been
              down for more than 1 minutes.'
    - name: Host and hardware
      exporters:
        - name: node-exporter
          doc_url: https://github.com/prometheus/node_exporter
          rules:
            - name: Host out of memory
              description: Node memory is filling up (< 10% left)
              query: 'node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 10'
              severity: warning
              for: 2m
            - name: Host memory under memory pressure
              description: The node is under heavy memory pressure. High rate of major page faults
              query: 'rate(node_vmstat_pgmajfault[1m]) > 1000'
              severity: warning
              for: 2m
            - name: Host unusual network throughput in
              description: Host network interfaces are probably receiving too much data (> 100 MB/s)
              query: 'sum by (instance) (rate(node_network_receive_bytes_total[2m])) / 1024 / 1024 > 100'
              severity: warning
              for: 5m
            - name: Host unusual network throughput out
              description: Host network interfaces are probably sending too much data (> 100 MB/s)
              query: 'sum by (instance) (rate(node_network_transmit_bytes_total[2m])) / 1024 / 1024 > 100'
              severity: warning
              for: 5m
            - name: Host unusual disk read rate
              description: Disk is probably reading too much data (> 50 MB/s)
              query: 'sum by (instance) (rate(node_disk_read_bytes_total[2m])) / 1024 / 1024 > 50'
              severity: warning
              for: 5m
            - name: Host unusual disk write rate
              description: Disk is probably writing too much data (> 50 MB/s)
              query: 'sum by (instance) (rate(node_disk_written_bytes_total[2m])) / 1024 / 1024 > 50'
              severity: warning
              for: 2m
            - name: Host out of disk space
              description: Disk is almost full (< 10% left)
              query: '(node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes < 10 and ON (instance, device, mountpoint) node_filesystem_readonly == 0'
              severity: warning
              comments: |
                Please add ignored mountpoints in node_exporter parameters like
                "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|run)($|/)".
                Same rule using "node_filesystem_free_bytes" will fire when disk fills for non-root users.
              for: 2m
            - name: Host disk will fill in 24 hours
              description: Filesystem is predicted to run out of space within the next 24 hours at current write rate
              query: '(node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes < 10 and ON (instance, device, mountpoint) predict_linear(node_filesystem_avail_bytes{fstype!~"tmpfs"}[1h], 24 * 3600) < 0 and ON (instance, device, mountpoint) node_filesystem_readonly == 0'
              severity: warning
              comments: |
                Please add ignored mountpoints in node_exporter parameters like
                "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|run)($|/)".
                Same rule using "node_filesystem_free_bytes" will fire when disk fills for non-root users.
              for: 2m
            - name: Host out of inodes
              description: Disk is almost running out of available inodes (< 10% left)
              query: 'node_filesystem_files_free{mountpoint ="/rootfs"} / node_filesystem_files{mountpoint="/rootfs"} * 100 < 10 and ON (instance, device, mountpoint) node_filesystem_readonly{mountpoint="/rootfs"} == 0'
              severity: warning
              for: 2m
            - name: Host inodes will fill in 24 hours
              description: Filesystem is predicted to run out of inodes within the next 24 hours at current write rate
              query: 'node_filesystem_files_free{mountpoint ="/rootfs"} / node_filesystem_files{mountpoint="/rootfs"} * 100 < 10 and predict_linear(node_filesystem_files_free{mountpoint="/rootfs"}[1h], 24 * 3600) < 0 and ON (instance, device, mountpoint) node_filesystem_readonly{mountpoint="/rootfs"} == 0'
              severity: warning
              for: 2m
            - name: Host unusual disk read latency
              description: Disk latency is growing (read operations > 100ms)
              query: 'rate(node_disk_read_time_seconds_total[1m]) / rate(node_disk_reads_completed_total[1m]) > 0.1 and rate(node_disk_reads_completed_total[1m]) > 0'
              severity: warning
              for: 2m
            - name: Host unusual disk write latency
              description: Disk latency is growing (write operations > 100ms)
              query: 'rate(node_disk_write_time_seconds_total[1m]) / rate(node_disk_writes_completed_total[1m]) > 0.1 and rate(node_disk_writes_completed_total[1m]) > 0'
              severity: warning
              for: 2m
            - name: Host high CPU load
              description: CPU load is > 80%
              query: '100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 80'
              severity: warning
            - name: Host CPU steal noisy neighbor
              description: CPU steal is > 10%. A noisy neighbor is killing VM performances or a spot instance may be out of credit.
              query: 'avg by(instance) (rate(node_cpu_seconds_total{mode="steal"}[5m])) * 100 > 10'
              severity: warning
            - name: Host context switching
              description: Context switching is growing on node (> 1000 / s)
              query: '(rate(node_context_switches_total[5m])) / (count without(cpu, mode) (node_cpu_seconds_total{mode="idle"})) > 1000'
              severity: warning
              comments: |
                1000 context switches is an arbitrary number.
                Alert threshold depends on nature of application.
                Please read: https://github.com/samber/awesome-prometheus-alerts/issues/58
            - name: Host swap is filling up
              description: Swap is filling up (>80%)
              query: '(1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes)) * 100 > 80'
              severity: warning
              for: 2m
            - name: Host systemd service crashed
              description: "systemd service crashed"
              query: 'node_systemd_unit_state{state="failed"} == 1'
              severity: warning
            - name: Host physical component too hot
              description: "Physical hardware component too hot"
              query: 'node_hwmon_temp_celsius > 75'
              severity: warning
              for: 5m
            - name: Host node overtemperature alarm
              description: "Physical node temperature alarm triggered"
              query: 'node_hwmon_temp_crit_alarm_celsius == 1'
              severity: critical
            - name: Host RAID array got inactive
              description: 'RAID array {{ $labels.device }} is in degraded state due to one or more disks failures. Number of spare drives is insufficient to fix issue automatically.'
              query: 'node_md_state{state="inactive"} > 0'
              severity: critical
            - name: Host RAID disk failure
              description: 'At least one device in RAID array on {{ $labels.instance }} failed. Array {{ $labels.md_device }} needs attention and possibly a disk swap'
              query: 'node_md_disks{state="failed"} > 0'
              severity: warning
              for: 2m
            - name: Host kernel version deviations
              description: Different kernel versions are running
              query: 'count(sum(label_replace(node_uname_info, "kernel", "$1", "release", "([0-9]+.[0-9]+.[0-9]+).*")) by (kernel)) > 1'
              severity: warning
              for: 6h
            - name: Host OOM kill detected
              description: OOM kill detected
              query: 'increase(node_vmstat_oom_kill[1m]) > 0'
              severity: warning
            - name: Host EDAC Correctable Errors detected
              description: 'Host {{ $labels.instance }} has had {{ printf "%.0f" $value }} correctable memory errors reported by EDAC in the last 5 minutes.'
              query: 'increase(node_edac_correctable_errors_total[1m]) > 0'
              severity: info
            - name: Host EDAC Uncorrectable Errors detected
              description: 'Host {{ $labels.instance }} has had {{ printf "%.0f" $value }} uncorrectable memory errors reported by EDAC in the last 5 minutes.'
              query: 'node_edac_uncorrectable_errors_total > 0'
              severity: warning
            - name: Host Network Receive Errors
              description: 'Host {{ $labels.instance }} interface {{ $labels.device }} has encountered {{ printf "%.0f" $value }} receive errors in the last five minutes.'
              query: 'rate(node_network_receive_errs_total[2m]) / rate(node_network_receive_packets_total[2m]) > 0.01'
              severity: warning
              for: 2m
            - name: Host Network Transmit Errors
              description: 'Host {{ $labels.instance }} interface {{ $labels.device }} has encountered {{ printf "%.0f" $value }} transmit errors in the last five minutes.'
              query: 'rate(node_network_transmit_errs_total[2m]) / rate(node_network_transmit_packets_total[2m]) > 0.01'
              severity: warning
              for: 2m
            - name: Host Network Interface Saturated
              description: 'The network interface "{{ $labels.interface }}" on "{{ $labels.instance }}" is getting overloaded.'
              query: '(rate(node_network_receive_bytes_total{device!~"^tap.*"}[1m]) + rate(node_network_transmit_bytes_total{device!~"^tap.*"}[1m])) / node_network_speed_bytes{device!~"^tap.*"} > 0.8'
              severity: warning
              for: 1m
            - name: Host conntrack limit
              description: 'The number of conntrack is approching limit'
              query: 'node_nf_conntrack_entries / node_nf_conntrack_entries_limit > 0.8'
              severity: warning
              for: 5m
            - name: Host clock skew
              description: 'Clock skew detected. Clock is out of sync.'
              query: '(node_timex_offset_seconds > 0.05 and deriv(node_timex_offset_seconds[5m]) >= 0) or (node_timex_offset_seconds < -0.05 and deriv(node_timex_offset_seconds[5m]) <= 0)'
              severity: warning
              for: 2m
            - name: Host clock not synchronising
              description: 'Clock not synchronising.'
              query: 'min_over_time(node_timex_sync_status[1m]) == 0 and node_timex_maxerror_seconds >= 16'
              severity: warning
              for: 2m
prometheus::scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: '10s'
    scrape_timeout: '10s'
    static_configs:
      - targets:
          - 'prometheus.home.vm:9090'
          - '192.168.0.107:9182'
        labels:
          alias: 'Prometheus'
  - job_name: 'node'
    scrape_interval: '10s'
    scrape_timeout: '10s'
    static_configs:
      - targets:
          - 'prometheus.home.vm:9100'
          - '192.168.0.107:9182'
          - 'foreman.home.vm:9100'
          - 'grafana.home.vm:9100'
        labels:
          alias: 'none'
