---
prometheus::manage_prometheus_server: true

prometheus::version: '2.27.0'

prometheus::alerts:
  groups:
    - name: 'alert.rules'
      rules:
        - alert: 'InstanceDown'
          expr: 'up == 0'
          for: '1m'
          labels:
            severity: 'page'
          annotations:
            summary: 'Instance {{ .Labels.instance }} {{ .Value }} down'
            description: '{{ $labels.instance }} of job {{ $labels.job }} has been
              down for more than 1 minutes.'
        - alert: PrometheusJobMissing
          expr: absent(up{job="prometheus"})
          for: 0m
          labels:
            severity: warning
          annotations:
            summary: Prometheus job missing (instance {{ $labels.instance }})
            description: "A Prometheus job has disappeared\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
        - alert: WindowsServerServiceStatus
          expr: windows_service_status{status="ok"} != 1
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: Windows Server service Status (instance {{ $labels.instance }})
            description: "Windows Service state is not OK\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
        - alert: WindowsServerDiskSpaceUsage
          expr: 100.0 - 100 * (((windows_logical_disk_free_bytes{volume!="HarddiskVolume2"}) / 1024 / 1024 ) / ((windows_logical_disk_size_bytes{volume!="HarddiskVolume2"}) / 1024 / 1024)) > 80
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: Windows Server disk Space Usage (instance {{ $labels.instance }})
            description: "Disk usage is more than 80%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
# Clock skew detected
        - alert: HostClockSkew
          expr: (node_timex_offset_seconds > 0.05 and deriv(node_timex_offset_seconds[5m]) >= 0) or (node_timex_offset_seconds < -0.05 and deriv(node_timex_offset_seconds[5m]) <= 0)
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: Host clock skew (instance {{ $labels.instance }})
            description: "Clock skew detected. Clock is out of sync.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

# Hyperv managemnt service
        - alert: WindowsHypervServiceStatus
          expr: windows_service_state{name="vmms", state="running"} == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: Windows Hyperv service Status (instance {{ $labels.instance }})
            description: "Windows Hyperv state is not OK\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
# windows_service_state service
        - alert: windows_exporterServiceStatus
          expr: windows_service_state{name="windows_exporter", state="running"} == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: Windows W32Time service Status (instance {{ $labels.instance }})
            description: "Windows windows_exporter state is not OK\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
# Audio
        - alert: WindowsAudioServiceStatus
          expr: windows_service_state{name="audiosrv", state="running"} == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: Windows Audio service Status (instance {{ $labels.instance }})
            description: "Windows Audio state is not OK\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
# 80% of mysql connections in use
        - alert: MysqlTooManyConnections(>80%)
          expr: avg by (instance) (rate(mysql_global_status_threads_connected[1m])) / avg by (instance) (mysql_global_variables_max_connections) * 100 > 80
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: MySQL too many connections (> 80%) (instance {{ $labels.instance }})
            description: "More than 80% of MySQL connections are in use on {{ $labels.instance }}\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
# SQL server down
        - alert: SqlServerDown
          expr: mssql_up == 0
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: SQL Server down (instance {{ $labels.instance }})
            description: "SQL server instance is down\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

prometheus::scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: '10s'
    scrape_timeout: '10s'
    static_configs:
      - targets:
          - 'prometheus.home.vm:9090'
          - 'prometheus.home.vm:9115'
          - 'foreman.home.vm:9100'
          - 'grafana.home.vm:9100'
          - '192.168.0.118:9100' #'raspberrypi.PK5001Z:9100'
        labels:
          alias: 'linux'
  - job_name: 'node'
    scrape_interval: '10s'
    scrape_timeout: '10s'
    static_configs:
      - targets:
          # - 'prometheus.home.vm:9100'
          - '192.168.0.107:9182'
        labels:
          alias: 'win'

prometheus::alertmanagers_config:
  - static_configs:
      - targets:
          - 'localhost:9093'

prometheus::alertmanager::version: '0.13.0'          

# scrape_configs:
#   - job_name: 'blackbox'
#     metrics_path: /probe
#     params:
#       module: [http_2xx]  # Look for a HTTP 200 response.
#     static_configs:
#       - targets:
#         - http://prometheus.io    # Target to probe with http.
#         - https://prometheus.io   # Target to probe with https.
#         - http://example.com:8080 # Target to probe with http on port 8080.
#     relabel_configs:
#       - source_labels: [__address__]
#         target_label: __param_target
#       - source_labels: [__param_target]
#         target_label: instance
#       - target_label: __address__
#         replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.
