forge 'https://forgeapi.puppetlabs.com'

mod 'saz-timezone', '6.1.0'
mod 'stm-debconf', '3.3.1'
mod 'puppetlabs/ntp'
mod 'puppet/selinux', '3.0.0'
mod 'puppetlabs/firewall', '3.0.0'
# mod 'juniorsysadmin/irqbalance', '1.1.0'
mod 'qtechnologies/sysstat', '1.2.0'
mod 'puppetlabs/sshkeys_core', '1.0.2'
mod 'puppetlabs-accounts', '7.0.2'
mod 'saz/sudo', '6.0.0'
mod 'puppetlabs-puppet_agent', '4.6.0'
mod 'saz/resolv_conf', '4.1.0'
mod 'saz/ssh', '6.0.0'
mod 'puppet/cron', '1.3.1'
mod 'puppet/r10k', '8.0.0'
mod 'camptocamp/systemd', '2.6.0'
mod 'bodgit/scl', '1.0.1'
mod 'puppet-dhcp'
mod 'puppetlabs-facts', '1.4.0'
mod 'puppetlabs/cron_core', '1.0.2'
mod 'puppetlabs/k5login_core', '1.0.2'
mod 'ghoneycutt/hosts', '2.7.0'
mod 'camptocamp/postfix', '1.8.0'
mod 'herculesteam-augeasproviders_core', '2.7.0'
mod 'herculesteam-augeasproviders_nagios', '2.1.1'
# mod 'puppetlabs-augeas_core', '1.1.2'
# mod 'camptocamp-augeas', '1.9.0'
# mod 'puppet/alternatives', '3.0.0'
# mod 'puppetlabs/mailalias_core', '1.0.5'
mod 'puppetlabs/docker', '3.8.0'
mod 'puppetlabs/reboot', '2.2.0'
# mod 'puppet/python', '3.0.1'
# mod 'derdanne/nfs', '2.1.2'
# mod 'jhoblitt/ipmi', '2.3.0'
mod 'puppet/lldpd', '2.2.0'
# mod 'puppet/rabbitmq', '10.0.1'
# mod 'puppet/redis', '6.0.0'
# mod 'puppetlabs/tomcat', '4.0.0'
mod 'puppet/nginx', '1.1.0'
mod 'puppet-prometheus', '11.0.0'
mod 'gulei-node_exporter', '1.0.0'
mod 'puppet/firewalld', '4.2.2'
mod 'mightp-influxdb', '1.0.3'
mod 'puppet-healthcheck', '1.0.1'
mod 'puppet-archive', '5.0.0'
mod 'puppet-grafana', '8.0.0'
mod 'puppetlabs-concat', '5.3.0'
mod 'puppetlabs-inifile', '5.0.1'
mod 'puppetlabs/java', '6.2.0'
mod 'puppetlabs-stdlib', '7.0.1'
mod 'puppetlabs/vcsrepo', '3.0.0'
mod 'puppet/rsyslog', '4.0.0'
mod 'puppet/ssh_keygen', '4.0.0'

# This requires toml-rb, which should be installed on the puppet master.
# @see profile::core::puppet_master
mod 'puppet/telegraf', '3.0.0'
mod 'puppetlabs-puppetserver_gem', '1.1.1'

mod 'puppet/yum', '4.0.0'
mod 'richardc/datacat', '0.6.2'
mod 'puppet-epel', '3.0.1'

mod 'simp/x2go', '0.2.1'
mod 'simp/mate', '1.0.2'
mod 'simp/dconf', '0.0.3'
mod 'simp/gnome', '8.1.1'
mod 'simp/polkit', '6.2.0'
mod 'simp/simplib', '3.15.3'

mod 'puppetlabs/mysql', '10.4.0'
mod 'puppetlabs/apache', '6.0.0'
mod 'puppetlabs/apt', '7.0.1'
mod 'puppetlabs/kubernetes', '4.0.1'
mod 'puppetlabs/lvm', '1.3.0'
mod 'puppetlabs/mount_providers', '2.0.1'
mod 'puppetlabs/xinetd', '3.3.0'
mod 'thrnio/ip', '1.0.1'
mod 'link0-nrpe', '0.0.3'
mod 'jgazeley-nagios', '0.4.0'
mod 'dalen-dnsquery', '3.0.0'

# mod 'woodsbw/augeasfacter', git: 'https://github.com/woodsbw/augeasfacter', commit: '9aea81311d277ed7ff1e8f2d4f79d13cd25f6ded'
# Encryption
mod 'puppetlabs-hocon', '1.1.0'
mod 'puppetlabs-puppet_authorization', '0.5.1'
mod 'binford2k-node_encrypt', '0.4.1'
# Windows 
mod 'puppetlabs-chocolatey', '6.0.0'
mod 'puppetlabs-registry', '4.0.0'
mod 'puppetlabs-powershell', '5.0.0'
mod 'puppetlabs-pwshlib', '0.8.0'
mod 'puppet-nsclient', '2.1.0'
mod 'puppet-download_file', '4.0.0'
mod 'puppetlabs-amazon_aws', '0.3.0'
mod 'lcrownover-facter', '0.2.3'
mod 'genebean-nxlog', '2.0.0'
