---
classes:
  - profile::default
  - profile::it::prometheus
profile::it::prometheus::slackuser_hide: it_alerts
profile::it::prometheus::slackapi_hide: ENC[PKCS7,MIIBygYJKoZIhvcNAQcDoIIBuzCCAbcCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAgRqgWBYksizx+LBNx3y77/6j/p0TFpfGFGUeQT674z8PnnXFlEnHXtkBV1T4MSelgIOLFRSnN75y8jDNInQW5bK1yvSEOZN3jcGGRAwXguY528Ll7Tq8jKyGyTJdYApL4smC2SgYyINnKOQ4ln+HgJj5yRa1kGvkH5aej0CVhfDaroqY4R/0mHV3ilNmXXygeGd9BF4s5Xye6iYGMyzjmkPuFlbwDtEC4JkmtR4/ZnWGdZ+CAEbXnKnDu05Z7u4vhZAJgFMrsRr1pZ0x78WHU07B9sSs6/GIcRMwtkhmKQD9I79CCJy2dTR6kdg9+OyS6AhJMvhxR4/iMOKfwQCTnzCBjAYJKoZIhvcNAQcBMB0GCWCGSAFlAwQBKgQQGuJoZ7KDnS455aU3AXHyi4BgLyRHv6FzaUdlNi3XMga3Fsci0io04pj9w4RbzDhqimtMiMEYfBO2RW0ucv9mxg6NJDpq25nKJjxSZj+yYJW1Bjimr/XdnPOhH/6ZzF68Qlcd8IGkmaVczOeLuZPe8l4c]
profile::it::prometheus::cluster_hide: ENC[PKCS7,MIIBiQYJKoZIhvcNAQcDoIIBejCCAXYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEASHm0n3F6Ppb6pbyoly31ph6qhkthp97gAlxria1IecI7/m5t1JXiiLNQahQY3I6MoS8Lkmfg+O/+Biz8hIqWkaGcGLOYs3h04ByTM3AFV9atPHDYMd643JyC+QMRcpialEZuY08ygdP7iDBhHA6RPOmh8vwV84K5nH47Hx3ftxP/d79Fs0TlQ31GyCjpo5AmbhnNimucAqMEtHlTmEXcgzHIedYwHIS4hJ6jN7CUj1E7cO2dDTQ9S0B6tc7QIGkphjJM1mrJRnuK9Oaw6qNdIvTX++MPss6BI4St7dNpiuqN+zpjxoWlqb+Xnj+BGelbeSdKd66YayJPEa+1uMFJwjBMBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBCftAVt9UohDUeVGFooIuVSgCAJTqUlyJNR8fqIoSaOh8vZvpv/Z7kZTqYCOYE7ZkYHCw==]
profile::it::prometheus::server_ip: "%{serverip}"
profile::it::prometheus::advertise_ip: 192.168.0.51:9093
# network::hostname: "%{facts.fqdn}"
network::interfaces_hash:
  eth1:
    ipaddress: 192.168.10.22
    netmask: 255.255.255.0
    dns1: 192.168.0.1
    peerdns: 'yes'
    bootproto: none
    onboot: 'yes'
  eth0:
    ipaddress: '192.168.0.51'
    netmask: '255.255.255.0'
    gateway: '192.168.0.1'
    dns1: 192.168.0.1
    dns2: 8.8.8.8
    peerdns: 'yes'
    bootproto: none
    onboot: 'yes'
# network::mroutes_hash:
#   eth1:
#     routes:
#       192.168.10.0/24: 'eth0'
