---
classes:
  - profile::default
  - profile::it::prometheus
profile::it::prometheus::slackuser_hide: ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEA5dTKg0AzGY+/Pf3Zl9sQIxIir7t4CNIkGotL+M9KlOjd2R1vjgWqP+dSMUAyQ414xUBktw6r+rV5Tfuu+zP1VFAUPWplSKcTTTeiWxpixFcTLoP//Su56CRMlHUL9RF6Y7d3nZklZjZITxOnOhFRNNwRPzW/lR+vJd4dlUVCpLbNGL6RJCopJk9R0um72bvSj0ea/aFYBIY3I+IgBUAOoAdbqQarrRowF239moLQG1J5F3HFZKVJIeZfYXqUCbEW4VQM5ebq5g5q5Ll5gHgt9SM+B0taFTZ/w1Wgzm2FP1nZ7yc+ghnTzpp+FvmmJZPJol08FxJTnP40QZJve13FjzA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBA1WcgcZwoEwEWCmWOX1OzbgBCRhsJoIKlsZSQIqN+ll6JF]
profile::it::prometheus::slackapi_hide: ENC[PKCS7,MIIBygYJKoZIhvcNAQcDoIIBuzCCAbcCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAm4YYbWffAU4DgZCmlLE4mWpX2btRxkB3ge/CdoOPnSC2LRt1Zwrz6mCv49Q3h046v7qGDq27BQTA2liX53TkBsNNPGvunxBDLaEmB1L2ROBH9F3Z/vbFQdqY7SGuWGNFooTF5Y6G/fqZ+Hl6a8AZZ6hD5zmVqRaO4ZyAKfnonwResuCrYekYHcyC0AxjQ2R52Szd2YOrWj4VYLSLDL/qGL2Cc1UA1LFhELV/80DaVudk356I8OjF0a8NgsVbjYImSeE4jBDjPTKgqTLHZl/DCRubOPqjU566k1yo5x4jtUlt8o5zvLoBhXVtCkh1VxJ/fKK5aArYqbVHbt95UcKmeDCBjAYJKoZIhvcNAQcBMB0GCWCGSAFlAwQBKgQQUja2+U9HKxM/Bids/rhII4BgULObpc1j3HIyX1bc6dj1aN2gUQGqmmrQ08RThttTwPgSOSM/ugX3fkA9EsqbzRM0XaXX8KeG7HtWs3tAPtbKTqzgQ5fwaFqkiKfG3DXgocG5Iv49NJYS4M9l/bhvPAb4]
profile::it::prometheus::cluster_hide: ENC[PKCS7,MIIBiQYJKoZIhvcNAQcDoIIBejCCAXYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAuiaI5JHPSxUbcevECZ5T+TcFvlybJV03g+Z+lhlJcq+M+hreMOPUpPzLfT0VEbkFDrLCuek/kwacpT4dTsqTX/dcVXucc1/gZfnnmSvC7Qk65zWCPi/ccOhvqv0rTAom3HArBmaxJ3FXiILORPbZC8b4MFJX+X/DqT01GkEEKFdTQUzgHEoAwIDuepabHMfUnVHKVtl/hk35yfNmCzJKPV/i0vYzuHxovD8zs/JmbS03T5hYubbN03G4Fi0IUMe3Vbhdg3mk2jaDLZ2zTkq8pDnksu5DSSsXKHI1kPjBkjdOFrlr87QiqWyJbYZWSKuIpwPyreRuu065k3OV5L1XujBMBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBAYaHgM3SaeccDf25e4KqW+gCBx44rzLWJw0VGbpgFJv+g2MHdI0E/d/1bo4HWhK6Mb0g==]
profile::it::prometheus::advertise_ip: 192.168.0.49:9093
profile::it::prometheus::server_ip: "%{serverip}"
network::interfaces_hash:
  eth1:
    ipaddress: '192.168.10.21'
    netmask: '255.255.255.0'
    dns1: "192.168.0.1"
    peerdns: 'yes'
    bootproto: 'static'
    onboot: 'no'

# network::mroutes_hash:
#   eth1:
#     routes:
#       192.168.10.0/24: eth0
