---
classes:
  - profile::default
  - profile::it::prometheus
profile::it::prometheus::slackuser_hide: it_alerts
profile::it::prometheus::slackapi_hide: https://hooks.slack.com/services/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
profile::it::prometheus::cluster_hide: ENC[PKCS7,MIIBiQYJKoZIhvcNAQcDoIIBejCCAXYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEASHm0n3F6Ppb6pbyoly31ph6qhkthp97gAlxria1IecI7/m5t1JXiiLNQahQY3I6MoS8Lkmfg+O/+Biz8hIqWkaGcGLOYs3h04ByTM3AFV9atPHDYMd643JyC+QMRcpialEZuY08ygdP7iDBhHA6RPOmh8vwV84K5nH47Hx3ftxP/d79Fs0TlQ31GyCjpo5AmbhnNimucAqMEtHlTmEXcgzHIedYwHIS4hJ6jN7CUj1E7cO2dDTQ9S0B6tc7QIGkphjJM1mrJRnuK9Oaw6qNdIvTX++MPss6BI4St7dNpiuqN+zpjxoWlqb+Xnj+BGelbeSdKd66YayJPEa+1uMFJwjBMBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBCftAVt9UohDUeVGFooIuVSgCAJTqUlyJNR8fqIoSaOh8vZvpv/Z7kZTqYCOYE7ZkYHCw==]
profile::it::prometheus::server_ip: "%{serverip}"
profile::it::prometheus::advertise_ip: 192.168.0.51:9093
# network::hostname: "%{facts.fqdn}"
network::interfaces_hash:
  eth1:
    ipaddress: 192.168.10.22
    netmask: 255.255.255.0
    dns1: 192.168.0.1
    peerdns: 'yes'
    bootproto: none
    onboot: 'yes'
  eth0:
    ipaddress: '192.168.0.51'
    netmask: '255.255.255.0'
    gateway: '192.168.0.1'
    dns1: 192.168.0.1
    dns2: 8.8.8.8
    peerdns: 'yes'
    bootproto: none
    onboot: 'yes'
# network::mroutes_hash:
#   eth1:
#     routes:
#       192.168.10.0/24: 'eth0'
