---
classes:
  - profile::default
  - profile::it::prometheus
profile::it::prometheus::slackuser_hide: ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEA5dTKg0AzGY+/Pf3Zl9sQIxIir7t4CNIkGotL+M9KlOjd2R1vjgWqP+dSMUAyQ414xUBktw6r+rV5Tfuu+zP1VFAUPWplSKcTTTeiWxpixFcTLoP//Su56CRMlHUL9RF6Y7d3nZklZjZITxOnOhFRNNwRPzW/lR+vJd4dlUVCpLbNGL6RJCopJk9R0um72bvSj0ea/aFYBIY3I+IgBUAOoAdbqQarrRowF239moLQG1J5F3HFZKVJIeZfYXqUCbEW4VQM5ebq5g5q5Ll5gHgt9SM+B0taFTZ/w1Wgzm2FP1nZ7yc+ghnTzpp+FvmmJZPJol08FxJTnP40QZJve13FjzA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBA1WcgcZwoEwEWCmWOX1OzbgBCRhsJoIKlsZSQIqN+ll6JF]
profile::it::prometheus::slackapi_hide: ENC[PKCS7,MIIBygYJKoZIhvcNAQcDoIIBuzCCAbcCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAgRqgWBYksizx+LBNx3y77/6j/p0TFpfGFGUeQT674z8PnnXFlEnHXtkBV1T4MSelgIOLFRSnN75y8jDNInQW5bK1yvSEOZN3jcGGRAwXguY528Ll7Tq8jKyGyTJdYApL4smC2SgYyINnKOQ4ln+HgJj5yRa1kGvkH5aej0CVhfDaroqY4R/0mHV3ilNmXXygeGd9BF4s5Xye6iYGMyzjmkPuFlbwDtEC4JkmtR4/ZnWGdZ+CAEbXnKnDu05Z7u4vhZAJgFMrsRr1pZ0x78WHU07B9sSs6/GIcRMwtkhmKQD9I79CCJy2dTR6kdg9+OyS6AhJMvhxR4/iMOKfwQCTnzCBjAYJKoZIhvcNAQcBMB0GCWCGSAFlAwQBKgQQGuJoZ7KDnS455aU3AXHyi4BgLyRHv6FzaUdlNi3XMga3Fsci0io04pj9w4RbzDhqimtMiMEYfBO2RW0ucv9mxg6NJDpq25nKJjxSZj+yYJW1Bjimr/XdnPOhH/6ZzF68Qlcd8IGkmaVczOeLuZPe8l4c]
profile::it::prometheus::cluster_hide: ENC[PKCS7,MIIBiQYJKoZIhvcNAQcDoIIBejCCAXYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAuiaI5JHPSxUbcevECZ5T+TcFvlybJV03g+Z+lhlJcq+M+hreMOPUpPzLfT0VEbkFDrLCuek/kwacpT4dTsqTX/dcVXucc1/gZfnnmSvC7Qk65zWCPi/ccOhvqv0rTAom3HArBmaxJ3FXiILORPbZC8b4MFJX+X/DqT01GkEEKFdTQUzgHEoAwIDuepabHMfUnVHKVtl/hk35yfNmCzJKPV/i0vYzuHxovD8zs/JmbS03T5hYubbN03G4Fi0IUMe3Vbhdg3mk2jaDLZ2zTkq8pDnksu5DSSsXKHI1kPjBkjdOFrlr87QiqWyJbYZWSKuIpwPyreRuu065k3OV5L1XujBMBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBAYaHgM3SaeccDf25e4KqW+gCBx44rzLWJw0VGbpgFJv+g2MHdI0E/d/1bo4HWhK6Mb0g==]
profile::it::prometheus::advertise_ip: 192.168.0.49:9093
profile::it::prometheus::server_ip: "%{serverip}"
network::interfaces_hash:
  eth1:
    ipaddress: 192.168.10.21
    netmask: 255.255.255.0
    dns1: 192.168.0.1
    peerdns: 'yes'
    bootproto: 'none'
    onboot: 'yes'
  eth0:
    ipaddress: '192.168.0.49'
    netmask: '255.255.255.0'
    gateway: '192.168.0.1'
    dns1: 192.168.0.1
    dns2: 8.8.8.8
    peerdns: 'yes'
    bootproto: none
    onboot: 'yes'

# network::mroutes_hash:
#   eth1:
#     routes:
#       192.168.10.0/24: eth0
